import FormalConjectures.Util.ProblemImports

/-!
# Erdős Problem 330

This file records the proof-faithful upper-density formulation that matches
the Turturean-style roadmap, rather than the older `answer(sorry)` statement
from Formal Conjectures.

The main theorem is currently packaged as a `Prop` target so this development
can remain `sorry`-free while the construction is formalized.
-/

noncomputable section

namespace Erdos330Formalization

open Set
open scoped Pointwise

/-- Exact two-fold sumset, allowing the two summands to be equal. -/
def twoFold (A : Set ℕ) : Set ℕ :=
  {n | ∃ x ∈ A, ∃ y ∈ A, x + y = n}

/-- Exact two-fold sumset generated by a finite set. -/
def twoFoldFinset (S : Finset ℕ) : Set ℕ :=
  {n | ∃ x ∈ S, ∃ y ∈ S, x + y = n}

/-- Exact order-two asymptotic basis property for subsets of `ℕ`. -/
def IsAsymptoticBasisTwo (A : Set ℕ) : Prop :=
  ∃ N : ℕ, ∀ n : ℕ, N ≤ n → n ∈ twoFold A

/-- Sums represented by `A` that stop being represented after removing `a`. -/
def privateSet (A : Set ℕ) (a : ℕ) : Set ℕ :=
  twoFold A \ twoFold (A \ {a})

/-- Positive upper asymptotic density. -/
def HasPositiveUpperDensity (A : Set ℕ) : Prop :=
  0 < A.upperDensity

/--
Proof-faithful target for Erdős Problem 330 in the exact two-fold,
positive-upper-density form.
-/
def MainTarget : Prop :=
  ∃ A : Set ℕ,
    IsAsymptoticBasisTwo A ∧
    HasPositiveUpperDensity A ∧
    ∀ a ∈ A, HasPositiveUpperDensity (privateSet A a)

theorem mainTarget_iff :
    MainTarget ↔
      ∃ A : Set ℕ,
        IsAsymptoticBasisTwo A ∧
        0 < A.upperDensity ∧
        ∀ a ∈ A, 0 < (privateSet A a).upperDensity := by
  rfl

theorem mem_twoFold {A : Set ℕ} {n : ℕ} :
    n ∈ twoFold A ↔ ∃ x ∈ A, ∃ y ∈ A, x + y = n := by
  rfl

theorem mem_twoFoldFinset {S : Finset ℕ} {n : ℕ} :
    n ∈ twoFoldFinset S ↔ ∃ x ∈ S, ∃ y ∈ S, x + y = n := by
  rfl

theorem twoFoldFinset_eq_twoFold_coe (S : Finset ℕ) :
    twoFoldFinset S = twoFold {n : ℕ | n ∈ S} := by
  rfl

theorem twoFold_mono {A B : Set ℕ} (hAB : A ⊆ B) :
    twoFold A ⊆ twoFold B := by
  intro n hn
  rcases hn with ⟨x, hx, y, hy, hxy⟩
  exact ⟨x, hAB hx, y, hAB hy, hxy⟩

theorem twoFoldFinset_mono {S T : Finset ℕ} (hST : S ⊆ T) :
    twoFoldFinset S ⊆ twoFoldFinset T := by
  intro n hn
  rcases hn with ⟨x, hx, y, hy, hxy⟩
  exact ⟨x, hST hx, y, hST hy, hxy⟩

theorem twoFold_eq_add (A : Set ℕ) :
    twoFold A = A + A := by
  rfl

theorem mem_privateSet {A : Set ℕ} {a n : ℕ} :
    n ∈ privateSet A a ↔
      n ∈ twoFold A ∧ n ∉ twoFold (A \ {a}) := by
  rfl

theorem privateSet_eq_add_diff (A : Set ℕ) (a : ℕ) :
    privateSet A a = (A + A) \ ((A \ {a}) + (A \ {a})) := by
  rw [privateSet, twoFold_eq_add A, twoFold_eq_add (A \ {a})]

theorem isAsymptoticBasisTwo_iff_add {A : Set ℕ} :
    IsAsymptoticBasisTwo A ↔ ∃ N : ℕ, ∀ n : ℕ, N ≤ n → n ∈ A + A := by
  unfold IsAsymptoticBasisTwo
  rw [twoFold_eq_add A]

end Erdos330Formalization
